export const designTemplateConfig = {
  quote: "",
  subQuote: "",
  brandHandle: "",
  imageURL: "",
  imageURL2: "",
  mainContentPadding: "",
  mainContentFontStyles: "",
  subContentFontStyles: "",
  brandingFontStyles: "",
  bgColorStyles: "",
  bgOpacity: "",
};

export const SampleDefaultData = {
  // horizontal templates
  HorizontalLeftImage: {
    quote: "",
    subQuote: "",
    brandHandle: "",
    imageURL: "",
    imageURL2: "",
    mainContentPadding: "",
    mainContentFont: "",
    mainContentFontSize: "",
    mainContentFontWeight: "",
    bgColor: "",
    bgOpacity: "",
  },

  HorizontalPoppedTitle: {
    quote: "",
    subQuote: "",
    brandHandle: "",
    imageURL: "",
    imageURL2: "",
    mainContentPadding: "",
    mainContentFont: "",
    mainContentFontSize: "",
    mainContentFontWeight: "",
    bgColor: "",
    bgOpacity: "",
  },

  HorizontalEncircledRightImage: {
    quote: "",
    subQuote: "",
    brandHandle: "",
    imageURL: "",
    imageURL2: "",
    mainContentPadding: "",
    mainContentFont: "",
    mainContentFontSize: "",
    mainContentFontWeight: "",
    bgColor: "",
    bgOpacity: "",
  },

  HorizontalPodcastGuest: {
    quote: "",
    subQuote: "",
    brandHandle: "",
    imageURL: "",
    imageURL2: "",
    mainContentPadding: "",
    mainContentFont: "",
    mainContentFontSize: "",
    mainContentFontWeight: "",
    bgColor: "",
    bgOpacity: "",
  },

  // square templates
  SquareBottomImage: {
    quote: "",
    subQuote: "",
    brandHandle: "",
    imageURL: "",
    imageURL2: "",
    mainContentPadding: "",
    mainContentFont: "",
    mainContentFontSize: "",
    mainContentFontWeight: "",
    bgColor: "",
    bgOpacity: "",
  },

  SquareEncircledTopImage: {
    quote: "",
    subQuote: "",
    brandHandle: "",
    imageURL: "",
    imageURL2: "",
    mainContentPadding: "",
    mainContentFont: "",
    mainContentFontSize: "",
    mainContentFontWeight: "",
    bgColor: "",
    bgOpacity: "",
  },

  SquareClippedTopImage: {
    quote:
      "Victorious warriors win first and then go to war, while defeated warriors go to war first and then seek to win.",
    subQuote: "Sun Tzu",
    brandHandle: "@wethesapiens_",
    imageURL: "https://pbs.twimg.com/media/Eu-1XoxUcAMhhsb.jpg",
    imageURL2: "",
    mainContentPadding: "",
    mainContentFont: "",
    mainContentFontSize: "",
    mainContentFontWeight: "",
    bgColor: "",
    bgOpacity: "",
  },

  SquareRightImage: {
    quote: "",
    subQuote: "",
    brandHandle: "",
    imageURL: "",
    imageURL2: "",
    mainContentPadding: "",
    mainContentFont: "",
    mainContentFontSize: "",
    mainContentFontWeight: "",
    bgColor: "",
    bgOpacity: "",
  },

  SquareWisdom: {
    quote: "",
    subQuote: "",
    brandHandle: "",
    imageURL: "",
    imageURL2: "",
    mainContentPadding: "",
    mainContentFont: "",
    mainContentFontSize: "",
    mainContentFontWeight: "",
    bgColor: "",
    bgOpacity: "",
  },

  SquareTwitter: {
    quote: "",
    subQuote: "",
    brandHandle: "",
    imageURL: "",
    imageURL2: "",
    mainContentPadding: "",
    mainContentFont: "",
    mainContentFontSize: "",
    mainContentFontWeight: "",
    bgColor: "",
    bgOpacity: "",
  },

  SquareQuote: {
    quote: "",
    subQuote: "",
    brandHandle: "",
    imageURL: "",
    imageURL2: "",
    mainContentPadding: "",
    mainContentFont: "",
    mainContentFontSize: "",
    mainContentFontWeight: "",
    bgColor: "",
    bgOpacity: "",
  },

  // vertical templates
  VerticalEncircledBottomImage: {
    quote: "",
    subQuote: "",
    brandHandle: "",
    imageURL: "",
    imageURL2: "",
    mainContentPadding: "",
    mainContentFont: "",
    mainContentFontSize: "",
    mainContentFontWeight: "",
    bgColor: "",
    bgOpacity: "",
  },

  VerticalBottomImage: {
    quote: "",
    subQuote: "",
    brandHandle: "",
    imageURL: "",
    imageURL2: "",
    mainContentPadding: "",
    mainContentFont: "",
    mainContentFontSize: "",
    mainContentFontWeight: "",
    bgColor: "",
    bgOpacity: "",
  },

  VerticalClippedBottomImage: {
    quote: "",
    subQuote: "",
    brandHandle: "",
    imageURL: "",
    imageURL2: "",
    mainContentPadding: "",
    mainContentFont: "",
    mainContentFontSize: "",
    mainContentFontWeight: "",
    bgColor: "",
    bgOpacity: "",
  },
};
